version: "3.9"

networks:
  default:
    driver: bridge

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vueapp
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
